import pandas as pd


#Establishing the end directory
# rule all:
#     input:
#         Here I place my final analysis. What is my final analysis?

# Determine pdb ids and chains.
rule pdb_ids:
    input:
        'data/proteins.tsv'
        
    output:
        'data/proteins_by_pdb.tsv'
        
    script:
        'scripts/pdb_ids.py'

# Determine the pdb files where both domains are at least 80% complete, where domain 1 is at least 80% complete, 
# where domain 2 is at least 80% complete, and where both domains are at least 60% complete. Determine the residues in each interface
# that are interacting using the 60% complete pdb files.
rule interface_analysis:
    input:
        'data/proteins_by_pdb.tsv',

    output:
        'data/proteins_pdb_summary.tsv',
        'data/proteins_pdb_both_80.tsv',
        'data/proteins_pdb_1_80.tsv',
        'data/proteins_pdb_2_80.tsv',
        'data/proteins_pdb_both_60.tsv',
        'data/proteins_interface.tsv'

    script:
        'scripts/interface_analysis.py'

# Don't need this 
# rule interface_residues:
#     input:
#         'data/proteins_pdb_best.tsv',

#     output:
#         'data/proteins_interface.tsv'

#     script:
#         'scripts/get_interface_all_aa.py'

# May not need this. If needed, could bundle into above step.
# rule convert_RCSB_cif_to_pdb:
#     input:
#         'data/proteins_pdb_best.tsv',
#         'data/input/RCSB_cif_best/'

#     output:
#         directory('data/input/RCSB/pdbs/')

#     script:
#         "scripts/rcsb_cif_to_pdb.py"

# Again, same as above.
# rule convert_AF_cif_to_pdb:
#     input:
#         'data/proteins_pdb_best.tsv',
#         'data/input/Alphafold_cif/'

#     output:
#         directory('data/output/RCSB_af_full/poly_g_6/')

#     script:
#         'scripts/af_cif_to_pdb.py'

# Will probably have to reconfigure this.
rule compare_structures_input:
    input:
        'proteins_pdb_best.tsv', #args.pdb_ids
        'input' #args.input_pdb_dir# args.linker_fasta_dir.

    output:
        directory('output') #args.output_dir

    shell:
        "python aa_main.py --config configs/input.ini"
#           Do I have to specify the scripts that will be used for this? Or will this automatically run it?


rule compare_structures_output:
    input:
        'proteins_pdb_best.tsv', #args.pdb_ids
        'input' #args.input_pdb_dir# args.linker_fasta_dir.

    output:
        'output' #args.output_dir

    shell:
        "python aa_main.py --config configs/output.ini"
